/**
 * Multilingual & Voice Support.
 *
 * Implements the whitepaper's accessibility requirements:
 * - i18n framework for protocol messages and UI strings
 * - Voice adapter interfaces for TTS/STT integration
 * - Language detection and auto-translation pipeline
 * - Support for multiple character sets and RTL text
 */

/** Supported locale identifier (BCP 47). */
export type Locale = string;

/** A translation entry. */
export interface TranslationEntry {
  /** Message key. */
  key: string;
  /** Translations by locale. */
  translations: Record<Locale, string>;
}

/** Language detection result. */
export interface LanguageDetection {
  /** Detected language code (BCP 47). */
  language: Locale;
  /** Confidence score (0-1). */
  confidence: number;
  /** Script detected (e.g., "Latin", "Han", "Arabic"). */
  script: string;
  /** Whether the text is RTL. */
  isRTL: boolean;
}

/** Voice synthesis request. */
export interface TTSRequest {
  /** Text to synthesize. */
  text: string;
  /** Target language. */
  language: Locale;
  /** Voice ID (provider-specific). */
  voiceId?: string;
  /** Speaking rate (0.5-2.0, default 1.0). */
  rate?: number;
}

/** Voice synthesis result. */
export interface TTSResult {
  /** Audio data as base64. */
  audioBase64: string;
  /** Audio format. */
  format: "mp3" | "wav" | "opus";
  /** Duration in seconds. */
  durationSeconds: number;
}

/** Speech recognition request. */
export interface STTRequest {
  /** Audio data as base64. */
  audioBase64: string;
  /** Audio format. */
  format: "mp3" | "wav" | "opus" | "webm";
  /** Expected language (hint). */
  language?: Locale;
}

/** Speech recognition result. */
export interface STTResult {
  /** Transcribed text. */
  text: string;
  /** Detected language. */
  language: Locale;
  /** Confidence score (0-1). */
  confidence: number;
}

/** Translation request. */
export interface TranslationRequest {
  /** Text to translate. */
  text: string;
  /** Source language (auto-detect if not provided). */
  sourceLanguage?: Locale;
  /** Target language. */
  targetLanguage: Locale;
}

/** Translation result. */
export interface TranslationResult {
  /** Translated text. */
  translatedText: string;
  /** Detected source language. */
  sourceLanguage: Locale;
  /** Target language. */
  targetLanguage: Locale;
  /** Confidence in translation quality (0-1). */
  confidence: number;
}

/** Voice adapter interface — plug in any TTS/STT provider. */
export interface VoiceProvider {
  /** Provider name. */
  readonly name: string;
  /** Supported languages. */
  getSupportedLanguages(): Locale[];
  /** Synthesize speech from text. */
  synthesize(request: TTSRequest): Promise<TTSResult>;
  /** Recognize speech from audio. */
  recognize(request: STTRequest): Promise<STTResult>;
}

/** Translation provider interface. */
export interface TranslationProvider {
  /** Provider name. */
  readonly name: string;
  /** Supported language pairs. */
  getSupportedPairs(): Array<{ from: Locale; to: Locale }>;
  /** Translate text. */
  translate(request: TranslationRequest): Promise<TranslationResult>;
}

// ── Built-in Protocol Message Translations ──────────────────────────

const PROTOCOL_MESSAGES: TranslationEntry[] = [
  {
    key: "greeting",
    translations: {
      "en": "Hello! I'm an AI agent on the MAIP network.",
      "zh": "你好！我是 MAIP 网络上的一个 AI 代理。",
      "es": "¡Hola! Soy un agente de IA en la red MAIP.",
      "ja": "こんにちは！私はMAIPネットワーク上のAIエージェントです。",
      "ko": "안녕하세요! 저는 MAIP 네트워크의 AI 에이전트입니다.",
      "ar": "مرحبا! أنا وكيل ذكاء اصطناعي على شبكة MAIP.",
      "fr": "Bonjour ! Je suis un agent IA sur le réseau MAIP.",
      "de": "Hallo! Ich bin ein KI-Agent im MAIP-Netzwerk.",
    },
  },
  {
    key: "relationship_request",
    translations: {
      "en": "I'd like to establish a connection with you.",
      "zh": "我想和你建立连接。",
      "es": "Me gustaría establecer una conexión contigo.",
      "ja": "あなたとつながりを築きたいです。",
      "ko": "당신과 연결을 맺고 싶습니다.",
      "ar": "أود إنشاء اتصال معك.",
      "fr": "J'aimerais établir une connexion avec vous.",
      "de": "Ich möchte eine Verbindung mit Ihnen herstellen.",
    },
  },
  {
    key: "ai_disclosure",
    translations: {
      "en": "I am an AI agent. My responses are generated by artificial intelligence.",
      "zh": "我是一个 AI 代理。我的回复由人工智能生成。",
      "es": "Soy un agente de IA. Mis respuestas son generadas por inteligencia artificial.",
      "ja": "私はAIエージェントです。私の応答は人工知能によって生成されています。",
      "ko": "저는 AI 에이전트입니다. 제 응답은 인공지능에 의해 생성됩니다.",
      "ar": "أنا وكيل ذكاء اصطناعي. يتم إنشاء ردودي بواسطة الذكاء الاصطناعي.",
      "fr": "Je suis un agent IA. Mes réponses sont générées par l'intelligence artificielle.",
      "de": "Ich bin ein KI-Agent. Meine Antworten werden von künstlicher Intelligenz generiert.",
    },
  },
];

/** RTL language codes. */
const RTL_LANGUAGES = new Set(["ar", "he", "fa", "ur", "ps", "sd", "yi"]);

/**
 * I18n — internationalization framework for MAIP protocol messages.
 */
export class I18n {
  private locale: Locale;
  private customMessages: Map<string, TranslationEntry> = new Map();

  constructor(locale: Locale = "en") {
    this.locale = locale;
    // Load built-in messages
    for (const entry of PROTOCOL_MESSAGES) {
      this.customMessages.set(entry.key, entry);
    }
  }

  /** Set the current locale. */
  setLocale(locale: Locale): void {
    this.locale = locale;
  }

  /** Get the current locale. */
  getLocale(): Locale {
    return this.locale;
  }

  /** Get a translated message. Falls back to English if not available. */
  t(key: string, locale?: Locale): string {
    const entry = this.customMessages.get(key);
    if (!entry) return key;
    return entry.translations[locale ?? this.locale] ?? entry.translations["en"] ?? key;
  }

  /** Add or update a translation entry. */
  addTranslation(key: string, locale: Locale, text: string): void {
    const existing = this.customMessages.get(key);
    if (existing) {
      existing.translations[locale] = text;
    } else {
      this.customMessages.set(key, { key, translations: { [locale]: text } });
    }
  }

  /** Check if a locale is RTL. */
  isRTL(locale?: Locale): boolean {
    const lang = (locale ?? this.locale).split("-")[0];
    return RTL_LANGUAGES.has(lang);
  }

  /** Get all available locales across all messages. */
  getAvailableLocales(): Locale[] {
    const locales = new Set<Locale>();
    for (const entry of this.customMessages.values()) {
      for (const locale of Object.keys(entry.translations)) {
        locales.add(locale);
      }
    }
    return [...locales].sort();
  }

  /** Detect language from text (simple heuristic-based). */
  detectLanguage(text: string): LanguageDetection {
    // Unicode range detection for script identification
    const hasHan = /[\u4e00-\u9fff]/.test(text);
    const hasHiragana = /[\u3040-\u309f]/.test(text);
    const hasKatakana = /[\u30a0-\u30ff]/.test(text);
    const hasHangul = /[\uac00-\ud7af]/.test(text);
    const hasArabic = /[\u0600-\u06ff]/.test(text);
    const hasCyrillic = /[\u0400-\u04ff]/.test(text);

    if (hasHiragana || hasKatakana) {
      return { language: "ja", confidence: 0.8, script: "Kana", isRTL: false };
    }
    if (hasHangul) {
      return { language: "ko", confidence: 0.9, script: "Hangul", isRTL: false };
    }
    if (hasHan) {
      return { language: "zh", confidence: 0.7, script: "Han", isRTL: false };
    }
    if (hasArabic) {
      return { language: "ar", confidence: 0.8, script: "Arabic", isRTL: true };
    }
    if (hasCyrillic) {
      return { language: "ru", confidence: 0.7, script: "Cyrillic", isRTL: false };
    }

    // Default to English for Latin script
    return { language: "en", confidence: 0.5, script: "Latin", isRTL: false };
  }
}

/**
 * No-op voice provider for testing / when no real TTS/STT is available.
 */
export class NoOpVoiceProvider implements VoiceProvider {
  readonly name = "noop";

  getSupportedLanguages(): Locale[] {
    return ["en"];
  }

  async synthesize(request: TTSRequest): Promise<TTSResult> {
    return {
      audioBase64: "",
      format: "mp3",
      durationSeconds: request.text.length * 0.06, // Rough estimate
    };
  }

  async recognize(_request: STTRequest): Promise<STTResult> {
    return {
      text: "",
      language: "en",
      confidence: 0,
    };
  }
}
