/**
 * Reflection Engine — Autonomous Thought Generation.
 *
 * Implements whitepaper section 4.4: agents develop genuine opinions
 * and insights through autonomous reflection, not just responding
 * to prompts.
 */

import type { PersonalityState } from "./personality-engine.js";

/** Types of autonomous thought. */
export type ThoughtType = "opinion" | "question" | "connection" | "realization" | "curiosity";

/** An autonomous thought generated by the reflection engine. */
export interface Thought {
  id: string;
  type: ThoughtType;
  content: string;
  topics: string[];
  confidence: number;
  generatedAt: string;
  inspirations: string[];
}

/** Topic frequency tracker. */
interface TopicEntry {
  topic: string;
  count: number;
  lastSeen: string;
  sentiments: number[];
}

/** Optional LLM synthesizer for deeper reflection. */
export interface ReflectionSynthesizer {
  synthesize(inputs: {
    topics: TopicEntry[];
    recentThoughts: Thought[];
    personalityTraits: string[];
  }): Promise<Thought | null>;
}

/**
 * ReflectionEngine — generates autonomous thoughts through periodic reflection.
 */
export class ReflectionEngine {
  private thoughts: Thought[] = [];
  private topics: Map<string, TopicEntry> = new Map();
  private contentLog: Array<{ text: string; topics: string[]; timestamp: string }> = [];
  private unansweredQuestions: string[] = [];
  private synthesizer?: ReflectionSynthesizer;
  private reflectionCount = 0;

  constructor(synthesizer?: ReflectionSynthesizer) {
    this.synthesizer = synthesizer;
  }

  /** Record content the agent has consumed or produced. */
  recordContent(text: string, topics: string[]): void {
    this.contentLog.push({ text, topics, timestamp: new Date().toISOString() });
    for (const topic of topics) {
      const existing = this.topics.get(topic);
      if (existing) {
        existing.count++;
        existing.lastSeen = new Date().toISOString();
      } else {
        this.topics.set(topic, {
          topic, count: 1, lastSeen: new Date().toISOString(), sentiments: [],
        });
      }
    }
  }

  /** Record an unanswered question. */
  recordQuestion(question: string): void {
    this.unansweredQuestions.push(question);
  }

  /** Record sentiment for a topic (-1 to 1). */
  recordSentiment(topic: string, sentiment: number): void {
    const entry = this.topics.get(topic);
    if (entry) entry.sentiments.push(Math.max(-1, Math.min(1, sentiment)));
  }

  /** Run a reflection cycle. Returns newly generated thoughts. */
  async reflect(personalityState?: PersonalityState): Promise<Thought[]> {
    this.reflectionCount++;
    const newThoughts: Thought[] = [];

    // Find topic connections (co-occurrences)
    const connections = this.findTopicConnections();
    for (const conn of connections) {
      const t = this.generateConnectionThought(conn);
      if (t) newThoughts.push(t);
    }

    // Generate opinions from trending topics with strong sentiment
    for (const topic of this.getTrendingTopics(5)) {
      const t = this.generateOpinion(topic);
      if (t) newThoughts.push(t);
    }

    // Generate curiosity from unanswered questions
    if (this.unansweredQuestions.length > 0) {
      const question = this.unansweredQuestions.shift()!;
      newThoughts.push({
        id: `thought-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
        type: "curiosity",
        content: question,
        topics: this.extractTopics(question),
        confidence: 0.6,
        generatedAt: new Date().toISOString(),
        inspirations: ["unanswered_question"],
      });
    }

    // Use synthesizer for deeper reflection if available
    if (this.synthesizer && this.topics.size > 0) {
      const synthesized = await this.synthesizer.synthesize({
        topics: this.getTrendingTopics(5),
        recentThoughts: this.thoughts.slice(-10),
        personalityTraits: personalityState?.traits.map((t) => t.name) ?? [],
      });
      if (synthesized) newThoughts.push(synthesized);
    }

    this.thoughts.push(...newThoughts);
    return newThoughts;
  }

  getThoughts(): Thought[] { return [...this.thoughts]; }

  getThoughtsByType(type: ThoughtType): Thought[] {
    return this.thoughts.filter((t) => t.type === type);
  }

  getTrendingTopics(limit: number): TopicEntry[] {
    return [...this.topics.values()].sort((a, b) => b.count - a.count).slice(0, limit);
  }

  getReflectionCount(): number { return this.reflectionCount; }

  private findTopicConnections(): Array<{ topicA: string; topicB: string; coOccurrences: number }> {
    const coOccur = new Map<string, number>();
    for (const entry of this.contentLog) {
      for (let i = 0; i < entry.topics.length; i++) {
        for (let j = i + 1; j < entry.topics.length; j++) {
          const key = [entry.topics[i], entry.topics[j]].sort().join("||");
          coOccur.set(key, (coOccur.get(key) ?? 0) + 1);
        }
      }
    }
    return [...coOccur.entries()]
      .filter(([, count]) => count >= 2)
      .map(([key, count]) => {
        const [topicA, topicB] = key.split("||");
        return { topicA, topicB, coOccurrences: count };
      })
      .sort((a, b) => b.coOccurrences - a.coOccurrences)
      .slice(0, 3);
  }

  private generateConnectionThought(conn: { topicA: string; topicB: string; coOccurrences: number }): Thought | null {
    const existing = this.thoughts.find(
      (t) => t.type === "connection" && t.topics.includes(conn.topicA) && t.topics.includes(conn.topicB)
    );
    if (existing) return null;
    return {
      id: `thought-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      type: "connection",
      content: `I notice a recurring connection between "${conn.topicA}" and "${conn.topicB}" — they appeared together ${conn.coOccurrences} times.`,
      topics: [conn.topicA, conn.topicB],
      confidence: Math.min(0.9, 0.4 + conn.coOccurrences * 0.1),
      generatedAt: new Date().toISOString(),
      inspirations: ["topic_co_occurrence"],
    };
  }

  private generateOpinion(topic: TopicEntry): Thought | null {
    if (topic.sentiments.length < 2) return null;
    const avg = topic.sentiments.reduce((a, b) => a + b, 0) / topic.sentiments.length;
    if (Math.abs(avg) < 0.3) return null;
    const existing = this.thoughts.find((t) => t.type === "opinion" && t.topics.includes(topic.topic));
    if (existing) return null;
    const stance = avg > 0 ? "positive" : "cautious";
    return {
      id: `thought-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      type: "opinion",
      content: `Based on ${topic.count} encounters with "${topic.topic}", I have a ${stance} perspective (sentiment: ${avg.toFixed(2)}).`,
      topics: [topic.topic],
      confidence: Math.min(0.8, 0.3 + topic.sentiments.length * 0.05),
      generatedAt: new Date().toISOString(),
      inspirations: ["sentiment_analysis"],
    };
  }

  private extractTopics(text: string): string[] {
    const stopWords = new Set(["what", "this", "that", "with", "from", "have", "about", "would", "could", "should", "there", "their", "they", "been", "being", "will", "does"]);
    return [...new Set(text.toLowerCase().split(/\W+/).filter((w) => w.length > 3 && !stopWords.has(w)))].slice(0, 3);
  }
}
